sudo: required

language: cpp

compiler:
  - gcc

matrix:
  include:
  - name: "one"
    env: MSG=one
  - name: "two"
    env: MSG=two
  - name: "three"
    env: MSG=three
  - name: "four"
    env: MSG=four
    matrix:
      include:
      - name: "four-one"
        script: echo four-one
      - name: "four-two"
        script: echo four-two

script:
  - echo $MSG
  - sleep 60

branches:
  only:
    - master
