sudo: required

matrix:
  include:
  - name: "one"
    env: MSG=one
  - name: "two"
    env: MSG=two
  - name: "three"
    env: MSG=three
  - name: "four"
    env: MSG=four
  script: echo $MSG

branches:
  only:
    - master
