sudo: required

language: cpp

compiler:
  - gcc

cache:
  directories:
    - ./shared
    
jobs:
  include:
    - stage: build
      before_install: echo "before_install"
      script:
        - rm -rf ./shared/*
        - echo foo | tee > ./shared/output
        - ls -al ./shared/output
    - stage: test
      script:
        - ls -al ./shared/*
        - cat ./shared/*
    - stage: test
      script:
        - ls -al ./shared/*
        - cat ./shared/*

branches:
  only:
    - master
