sudo: required

language: cpp

compiler:
  - gcc

jobs:
  include:
    - stage: build
      before_install: mkdir -p ~/shared
      script:
        - echo foo | tee > ~/shared/output
        - ls -al ~/shared/output
      cache:
        directories:
          - ./shared/output
    - stage: test
      script: ls -al ~/shared/*
    - stage: test
      script: ls -al ~/shared/*

branches:
  only:
    - master
